### ISSUE TITLE
Consider benchmarking against  libpy_simdjson

### ISSUE THREAD

**Issue by lemire** [TkTech/pysimdjson#42] opened 2020-07-16 16:42 UTC
It looks like libpy_simdjson does much better on some benchmarks...

```
-------------------------------------------------------- benchmark 'Load /home/runner/work/libpy_simdjson/libpy_simdjson/libpy_simdjson/tests/jsonexamples/twitter.json': 6 tests -------------------------------------------------------
Name (time in us)                                          Min                    Max                  Mean                StdDev                Median                 IQR            Outliers         OPS            Rounds  Iterations
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_benchmark_load[path1-libpy_simdjson-loads]       374.2130 (1.0)      10,169.1400 (1.0)        445.6502 (1.0)        237.7491 (1.0)        443.3150 (1.0)       66.3020 (1.0)         19;29  2,243.9125 (1.0)        1790           1
test_benchmark_load[path1-orjson-loads]             2,788.1970 (7.45)     11,687.4110 (1.15)     3,351.3276 (7.52)     1,117.1151 (4.70)     3,198.9625 (7.22)     351.0120 (5.29)        10;12    298.3892 (0.13)        294           1
test_benchmark_load[path1-ujson-loads]              3,312.1150 (8.85)     12,571.4370 (1.24)     3,973.3347 (8.92)     1,221.4127 (5.14)     3,805.8815 (8.59)     447.3170 (6.75)          7;9    251.6778 (0.11)        258           1
test_benchmark_load[path1-pysimdjson-loads]         3,586.0280 (9.58)     18,704.8590 (1.84)     4,553.9661 (10.22)    1,772.5065 (7.46)     4,182.3480 (9.43)     331.1612 (4.99)         7;17    219.5888 (0.10)        169           1
test_benchmark_load[path1-python_json-loads]        4,573.6530 (12.22)    13,900.1650 (1.37)     5,396.5765 (12.11)    1,236.4753 (5.20)     5,222.7750 (11.78)    554.0430 (8.36)          6;7    185.3027 (0.08)        189           1
test_benchmark_load[path1-rapidjson-loads]          5,447.2870 (14.56)    16,226.5570 (1.60)     6,506.3766 (14.60)    1,495.7694 (6.29)     6,322.1140 (14.26)    544.9407 (8.22)          6;7    153.6954 (0.07)        165           1
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by TkTech** [comment] 2020-07-16 17:13
Doesn't look like it does, it's "cheating". We benchmark against full "uplifting" of objects - that is, the entire structure is available after calling loads(), just like it is in every other JSON decoder. Skimming libpy_simdjson and its benchmark, it's using delayed evaluation of its arrays and dicts and benchmarking against that instead, while using `loads()` for everything it's comparing to. Their benchmark is the same as calling parse() and doing nothing with the result.
@lemire

**Comment by gerrymanoim** [comment] 2020-07-16 17:47
Hey - just wanted to chime in here. We know that pysimdjson is converting the full object and are working on benchmarks for "overhead over accessing a dict". However, by design, libpy_simdjson will avoid converting to Python types until as late as possible (on specific attribute access). A goal of `libpy_simdjson` (and `libpy`) is to provide proxy objects that can be used as as if they were actual python objects without incurring the cost of object conversion until actually needed.

**Comment by TkTech** [comment] 2020-07-17 20:52
@gerrymanoim you can do a fairer benchmark now, pysimdjson v2 was just released with similar support for transparent Objects and Arrays.

**Comment by TkTech** [comment] 2020-07-18 14:02
Working on adding libpy_simdjson to our benchmarks today, just re-working our benchmark harness so it's easier for us to add new ones.

**Comment by TkTech** [comment] 2020-10-28 17:48
These benchmarks are included on the libpy_simdjson repo. We should probably include these in ours at some point, but libpy_simdjson supports a smaller range of Python versions and compilers, and I don't yet have a mechanism for filtering the list of decoders based off of what platform we're on.

**Closed by TkTech** 2020-10-28 17:48 UTC
